import { Navbar } from '@components';
import { images } from '@constants';
import '@styles/base/globals.scss';

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
	return (
		<html lang='en'>
			<body
				style={{
					backgroundImage: `url(${images.wave.src})`,
					backgroundPosition: 'center',
					backgroundSize: 'cover',
					backgroundRepeat: 'repeat',
					backgroundAttachment: 'fixed',
				}}
				suppressHydrationWarning={true}>
				<Navbar />
				{children}
			</body>
		</html>
	);
}
