import { Navbar } from '@components';
import '@styles/base/globals.scss';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
	return (
		<html lang='en'>
			<body suppressHydrationWarning={true} className={inter.className}>
				<Navbar />
				{children}
			</body>
		</html>
	);
}
